version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - jenkins0
      - jenkins1

  jenkins0:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.jenkins0
      args:
        PORT: 8000
    ports:
      - 8000

  jenkins1:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.jenkins1
      args:
        PORT: 8000
    ports:
      - 8000

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd
