version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - master2603
      - master2463
    # volumes:
    #  - ./20-jenkins-test.conf:/etc/collectd/managed_config/20-jenkins-test.conf
    #  - ../jenkins.py:/opt/collectd-jenkins/jenkins.py

  master2603:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.jenkins.lts
      args:
        PORT: 8000
    ports:
      - "8003:8000"

  master2463:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.jenkins.lts
      args:
        PORT: 8000
    ports:
      - "8004:8000"

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink
    ports:
      - "8080:8080"

  test-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd
