version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - master2603
      - master2463

  master2603:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.jenkins.lts
      args:
        PORT: 8000
    ports:
      - 8000

  master2463:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.jenkins.lts
      args:
        PORT: 8000
    ports:
      - 8000

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd
